version: 0.1

phases:
  install:
    commands:
      - echo Installing yarn...
      - npm install yarn -g
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build successfully triggered
      - echo Deploying lambda functions...
      - zip -r deploy.zip *
      - aws lambda update-function-code --function-name voice-z-machine-interpreter --zip-file fileb://deploy.zip
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "build.zip"
